# Generated by Django 2.2 on 2021-04-20 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('releaseDate', models.IntegerField(default=2030)),
                ('description', models.TextField(default='')),
                ('assetUrl', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Concept Car',
                'verbose_name_plural': 'Concept Cars',
            },
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(default=0)),
                ('type', models.CharField(default='', max_length=50)),
                ('configuration', models.CharField(default='', max_length=50)),
                ('power', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Engine',
                'verbose_name_plural': 'Engines',
            },
        ),
        migrations.CreateModel(
            name='Gearbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=100)),
                ('gearCount', models.IntegerField(default=0)),
                ('clutchCount', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gearbox',
                'verbose_name_plural': 'Gearboxes',
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('url', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(default='', max_length=30)),
                ('body', models.CharField(default='', max_length=30)),
                ('photoForList', models.CharField(default='', max_length=200)),
                ('photoForShow', models.CharField(default='', max_length=200)),
                ('startingPrice', models.IntegerField(default=0)),
                ('dimensions', models.CharField(default='', max_length=100)),
                ('engine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='api.Engine')),
                ('gearBox', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='api.Gearbox')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
