# Generated by Django 2.2 on 2021-04-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='power',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='engine',
            name='volume',
            field=models.FloatField(default=0),
        ),
    ]
