# Generated by Django 2.2 on 2021-04-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210427_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='dimensions',
            field=models.CharField(default=',,', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='photoForList',
            field=models.CharField(default='../../../assets/images/.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='photoForShow',
            field=models.CharField(default='../../../assets/images/-STATE.jpg', max_length=200),
        ),
    ]
